# This is a basic workflow to help you get started with Actions

name: Example-Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    container: fedora:latest
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install rpm and copr tools
      - name: Install tooling for source RPM build
        run: dnf -y install @development-tools @rpm-development-tools copr-cli make

      # Get/download the source files to the right place
      - name: Get the sources for RPM package
        run: ./getsources.sh

      # Build the SRPM package
      - name: Build the source RPM
        run: cd rpm/SPECS && make rpmbuild -bs *.spec

